In [15]:
import pandas as pd

data = pd.read_csv("/content/advertising.csv")
data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,2016-02-11 21:49:00,1
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,2016-04-22 02:07:01,1
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,2016-02-01 17:24:57,1
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,2016-03-24 02:35:54,0
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,2016-06-03 21:43:21,1

In [2]:
df1 = data.drop(['Ad Topic Line', 'Timestamp'], axis=1)

In [3]:
df1_encoded = pd.get_dummies(df1, columns=['Country', 'City'])

In [4]:
X = df1_encoded.drop('Clicked on Ad', axis=1)
y = df1_encoded['Clicked on Ad']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svm_model = SVC()

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.68

In [8]:
svm_model_2 = SVC(kernel='rbf', C=10, gamma='scale')
svm_model_3 = SVC(kernel='poly', degree=3, C=1)

svm_model_2.fit(X_train, y_train)
svm_model_3.fit(X_train, y_train)

y_pred_2 = svm_model_2.predict(X_test)
y_pred_3 = svm_model_3.predict(X_test)

accuracy_2 = accuracy_score(y_test, y_pred_2)
accuracy_3 = accuracy_score(y_test, y_pred_3)

print("Accuracy with RBF kernel (C=10, gamma='scale'):", accuracy_2)
print("Accuracy with polynomial kernel (degree=3, C=1):", accuracy_3)

Accuracy with RBF kernel (C=10, gamma='scale'): 0.685
Accuracy with polynomial kernel (degree=3, C=1): 0.665

In [14]:
from sklearn.metrics import confusion_matrix, classification_report

# Evaluate the predictions using confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[74 15]
 [49 62]]

In [13]:
# Evaluate the predictions using classification report
cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.83      0.70        89
           1       0.81      0.56      0.66       111

    accuracy                           0.68       200
   macro avg       0.70      0.70      0.68       200
weighted avg       0.71      0.68      0.68       200

TP: 74
TN: 62
FP: 15
FN: 49

-------------------
Precision: 0.60
Recall: 0.83
F1-score: 0.70

-----------------------